// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/// @notice A contract that
contract Rehypothecation {

    /// @notice A function that collects the yield generated by the Pool.
    // function harvest() {}

}
